-- Official venue catalog from "Liste Club Padel.xlsx".
-- Keeps existing IDs to avoid breaking already generated matches.

UPDATE clubs SET name = 'Cana Beau Plan', short_name = 'CANA BP', logo_url = '/club-logos/cana-padel.png', venue_details = 'Lieu: Beau Plan | Zone: Nord | Terrains: 5', contact_name = 'Mathieu Vallet', contact_phone = '59792962', contact_email = NULL WHERE id = 1;
UPDATE clubs SET name = 'Club Med Albion', short_name = 'CLUB MED', logo_url = '/club-logos/club-med.png', venue_details = 'Lieu: Albion | Zone: Ouest | Terrains: 3', contact_name = 'Romain Beltrando', contact_phone = '59365037', contact_email = NULL WHERE id = 2;
UPDATE clubs SET name = 'Urban Sport Grand Baie', short_name = 'US GB', logo_url = '/club-logos/urban-sport.png', venue_details = 'Lieu: Grand Baie | Zone: Nord | Terrains: 3', contact_name = 'Pascal Hoffmann', contact_phone = '52580551', contact_email = NULL WHERE id = 3;
UPDATE clubs SET name = 'Urban Sport Black River', short_name = 'US BR', logo_url = '/club-logos/urban-sport.png', venue_details = 'Lieu: Black River | Zone: Ouest | Terrains: 4', contact_name = 'Pascal Hoffmann', contact_phone = '52580551', contact_email = NULL WHERE id = 4;
UPDATE clubs SET name = 'SPARC Cascavelle', short_name = 'SPARC', logo_url = '/club-logos/sparc.png', venue_details = 'Lieu: Cascavelle | Zone: Ouest | Terrains: 4', contact_name = 'Maxime Huyse', contact_phone = '54810753', contact_email = NULL WHERE id = 5;
UPDATE clubs SET name = 'RM Club Tamarin', short_name = 'RM TAM', logo_url = '/club-logos/rm-tamarin.png', venue_details = 'Lieu: Tamarin | Zone: Ouest | Terrains: 5', contact_name = 'Coline Aumard', contact_phone = '55080718', contact_email = NULL WHERE id = 6;
UPDATE clubs SET name = 'I Padel by RM Hennessy', short_name = 'IPADEL H', logo_url = '/club-logos/ipadel-rm.png', venue_details = 'Lieu: Hennessy | Zone: Centre | Terrains: 4', contact_name = 'Coline Aumard', contact_phone = '55080718', contact_email = NULL WHERE id = 7;
UPDATE clubs SET name = 'RM Club Forbach', short_name = 'RM FOR', logo_url = '/club-logos/rm-grand-baie-v2.png', venue_details = 'Lieu: Grand Baie | Zone: Nord | Terrains: 7', contact_name = 'Coline Aumard', contact_phone = '55080718', contact_email = NULL WHERE id = 8;
UPDATE clubs SET name = 'Labourdonnais Mapou', short_name = 'LAB MAP', logo_url = '/club-logos/labourdonnais-v2.png', venue_details = 'Lieu: Mapou | Zone: Nord | Terrains: 3', contact_name = 'Mickael Gosch', contact_phone = '54752121', contact_email = NULL WHERE id = 9;
UPDATE clubs SET name = 'I Padel by RM Port Chambly', short_name = 'IPADEL PC', logo_url = '/club-logos/ipadel-rm.png', venue_details = 'Lieu: Port Chambly | Zone: Centre | Terrains: 3', contact_name = 'Coline Aumard', contact_phone = '55080718', contact_email = NULL WHERE id = 10;
UPDATE clubs SET name = 'Studio by RM Azuri', short_name = 'STUDIO RM', logo_url = '/club-logos/studio-rm.png', venue_details = 'Lieu: Azuri | Zone: Est | Terrains: 3', contact_name = 'Coline Aumard', contact_phone = '55080718', contact_email = NULL WHERE id = 11;
UPDATE clubs SET name = 'Isla Padel Grand Baie', short_name = 'ISLA GB', logo_url = '/club-logos/isla-padel-v2.png', venue_details = 'Lieu: Grand Baie | Zone: Nord | Terrains: 6', contact_name = 'Florian Manson', contact_phone = '57553320', contact_email = NULL WHERE id = 12;
UPDATE clubs SET name = 'Terres Brunes Sports & Leisure', short_name = 'TBRUNES', logo_url = '/club-logos/terres-brunes.png', venue_details = 'Lieu: Tamarin | Zone: Ouest | Terrains: 3', contact_name = 'Marinne Giraud', contact_phone = '54239475', contact_email = NULL WHERE id = 13;
UPDATE clubs SET name = 'Mont Choisy Golf', short_name = 'MCHOISY', logo_url = '/club-logos/mont-choisy.png', venue_details = 'Lieu: Mont Choisy | Zone: Nord | Terrains: 2', contact_name = 'Sarvish Kinnoo', contact_phone = '57726006', contact_email = NULL WHERE id = 14;
UPDATE clubs SET name = 'Oxygen Moka', short_name = 'OXYGEN', logo_url = '/club-logos/oxygen.png', venue_details = 'Lieu: Moka | Zone: Centre | Terrains: 2', contact_name = 'Matteo Zinno', contact_phone = '57463006', contact_email = NULL WHERE id = 15;
UPDATE clubs SET name = 'Club House Black River', short_name = 'CH BR', logo_url = '/club-logos/club-house-tamarin.png', venue_details = 'Lieu: Black River | Zone: Ouest | Terrains: 2', contact_name = 'Alexis Lavie', contact_phone = '54941771', contact_email = NULL WHERE id = 16;
UPDATE clubs SET name = 'Energia Pointe aux Canonniers', short_name = 'ENERGIA', logo_url = '/club-logos/energia.png', venue_details = 'Lieu: Pointe aux Canonniers | Zone: Nord | Terrains: 2', contact_name = 'Damien Putteea', contact_phone = '59386076', contact_email = NULL WHERE id = 17;
UPDATE clubs SET name = 'Moka Rangers', short_name = 'MOKA R', logo_url = NULL, venue_details = 'Lieu: Moka | Zone: Centre | Terrains: 4', contact_name = 'Mathias Ritter', contact_phone = '58013256', contact_email = NULL WHERE id = 18;

NOTIFY pgrst, 'reload schema';
